# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

steps:
  - checkout: self
    clean: true
    fetchDepth: 1
    persistCredentials: true

  - task: PowerShell@2
    displayName: "Configure user"
    inputs:
      targetType: "inline"
      script: |
        git config --global user.email "GraphTooling@service.microsoft.com"
        git config --global user.name "Microsoft Graph DevX Tooling"

  - task: CredScan@2
    displayName: 'Run CredScan'
    inputs:
      debugMode: false
      batchSize: 20
      toolMajorVersion: 'V2'
      searchersFileType: 'Skype'